application/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash
from werkzeug.exceptions import NotFound
from sqlalchemy import func, or_
from ipaddress import ip_network
from . import db
import json

from .models import InfrastructureCiscoAci, CiscoACISwitch, CiscoACISwitchVpcPairs, EnvironmentTypes, LocationItems, TenantItems, ZoneItems, IPAM_CIDRS, IPAM_HOSTS, DomainItems
from .functions import handle_terraform_files, handle_aci_fabric_node_member_data, handle_aci_vpc_explict_protection_group_data

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)
    
@views.route('/manage-portal', methods=['GET', 'POST'])
@login_required
def manage_portal():
    if request.method == 'POST' and 'manage_tenants_form' in request.form:
        tenant_name = request.form.get('tenant_name')
        
        existing_tenant = TenantItems.query.filter_by(tenant_name=tenant_name).first()
        if existing_tenant is not None:
            flash('Tenant already exists.', category='error')
        else:
            new_tenant = TenantItems(tenant_name=tenant_name)  # Adjust according to your model
            db.session.add(new_tenant)
            db.session.commit()
            flash('Tenant added successfully!', category='success')
            return redirect(url_for('views.manage_portal'))  # Redirect to clear the form/post request
    
    tenants = TenantItems.query.all()
    
    if request.method == 'POST' and 'manage_zones_form' in request.form:
        zone_name = request.form.get('zone_name')
        
        existing_zone = ZoneItems.query.filter_by(zone_name=zone_name).first()
        if existing_zone is not None:
            flash('zone already exists.', category='error')
        else:
            new_zone = ZoneItems(zone_name=zone_name)
            db.session.add(new_zone)
            db.session.commit()
            flash('zone added successfully!', category='success')
            return redirect(url_for('views.manage_portal'))
    
    zones = ZoneItems.query.all()
    
    if request.method == 'POST' and 'manage_envs_form' in request.form:
        env_name = request.form.get('env_name')
        
        existing_env = EnvironmentTypes.query.filter_by(types=env_name).first()
        if existing_env is not None:
            flash('env already exists.', category='error')
        else:
            new_env = EnvironmentTypes(types=env_name)
            db.session.add(new_env)
            db.session.commit()
            flash('env added successfully!', category='success')
            return redirect(url_for('views.manage_portal'))
    
    envs = EnvironmentTypes.query.all() 
    
    
    return render_template("manage_portal.html", user=current_user, tenants=tenants, zones=zones, envs=envs)   
    
@views.route('/delete-tenant/<int:id>', methods=['POST'])
@login_required
def delete_tenant(id):
    # Query the database for the infrastructure entry
    tenant_to_delete = TenantItems.query.get_or_404(id)

    # Delete the entry from the database
    db.session.delete(tenant_to_delete)
    db.session.commit()

    flash('Infrastructure entry deleted successfully!', category='success')
    return redirect(url_for('views.manage_portal')) 
    
@views.route('/delete-zone/<int:id>', methods=['POST'])
@login_required
def delete_zone(id):
    # Query the database for the infrastructure entry
    zone_to_delete = ZoneItems.query.get_or_404(id)

    # Delete the entry from the database
    db.session.delete(zone_to_delete)
    db.session.commit()

    flash('Infrastructure entry deleted successfully!', category='success')
    return redirect(url_for('views.manage_portal')) 
    
@views.route('/delete-env/<int:id>', methods=['POST'])
@login_required
def delete_env(id):
    # Query the database for the infrastructure entry
    env_to_delete = EnvironmentTypes.query.get_or_404(id)

    # Delete the entry from the database
    db.session.delete(env_to_delete)
    db.session.commit()

    flash('Infrastructure entry deleted successfully!', category='success')
    return redirect(url_for('views.manage_portal'))        

@views.route('/infrastructure', methods=['GET', 'POST'])
@login_required
def infrastructure():
    return render_template("infrastructure.html", user=current_user)
    
@views.route('/infrastructure/ciscoaci', methods=['GET', 'POST'])
@login_required
def infrastructure_ciscoaci():
    print("Entered infrastructure_ciscoaci route")
    # Initialize variables
    infrastructures = []
    fabric_names = []
    used_node_ids = []
    used_peer_ids = [] 
    available_node_ids = []
    available_peer_ids = []
    switches = []

    try:
        # Fetch all infrastructures and switches
        infrastructures = InfrastructureCiscoAci.query.with_entities(
            InfrastructureCiscoAci.id, 
            InfrastructureCiscoAci.fabric_name, 
            InfrastructureCiscoAci.target_apic, 
            InfrastructureCiscoAci.service_account_username,
            InfrastructureCiscoAci.git_repository,
            InfrastructureCiscoAci.git_username,
            InfrastructureCiscoAci.git_email
        ).all()
        switches = CiscoACISwitch.query.all()

        # Initialize lists for fabric names, available node IDs, and used peer IDs
        fabric_names = [inf.fabric_name for inf in infrastructures]
        used_node_ids = [switch.node_id for switch in switches]
        used_peer_ids = [switch.node_peer_id for switch in switches]
        available_node_ids = [i for i in range(101, 4001) if i not in used_node_ids]
        available_peer_ids = [i for i in range(101, 4001) if i not in used_peer_ids]

        # Handle Cisco ACI infrastructure form submission
        if request.method == 'POST' and 'infrastructure_form' in request.form:
            fabric_name = request.form.get('fabric_name')
            target_apic = request.form.get('target_apic')
            service_account_username = request.form.get('service_account_username')
            service_account_password = request.form.get('service_account_password')
            git_repository = request.form.get('git_repository')
            git_username = request.form.get('git_username')
            git_email = request.form.get('git_email')

            existing_apic = InfrastructureCiscoAci.query.filter_by(target_apic=target_apic).first()
            if existing_apic:
                flash('APIC IP already exists.', category='error')
            else:
                new_infrastructure = InfrastructureCiscoAci(
                    fabric_name=fabric_name,
                    target_apic=target_apic,
                    service_account_username=service_account_username,
                    service_account_password=generate_password_hash(service_account_password),
                    git_repository=git_repository,
                    git_username=git_username,
                    git_email=git_email
                )
                db.session.add(new_infrastructure)
                db.session.commit()
                flash('Infrastructure added successfully!', category='success')
                handle_terraform_files(git_repository, git_username, git_email)

            existing_locations = LocationItems.query.filter_by(items=fabric_name).first()
            if existing_locations:
                print(f"Location, {fabric_name} Exists")
            else:
                new_location = LocationItems(items=fabric_name)
                db.session.add(new_location)
                db.session.commit()
                flash('Location added successfully!', category='success')                

        # Handle switch form submission
        if request.method == 'POST' and 'switch_form' in request.form:
            print("Handling switch form submission")
            fabric_name = request.form.get('fabric_name')
            print(f"Fabric Name: {fabric_name}")
            node_role = request.form.get('node_role')
            pod_id = request.form.get('pod_id', type=int)
            node_id = request.form.get('node_id', type=int)
            node_peer_id = request.form.get('node_peer_id', type=int)
            serial_number = request.form.get('serial_number')
            node_name = request.form.get('node_name')

            # Logging or printing the extracted values for validation
            print(f"Attempting to add a new switch pair: Fabric Name={fabric_name}, Node ID={node_id}, Node Peer ID={node_peer_id}")
            

            existing_switch = CiscoACISwitch.query.filter_by(fabric_name=fabric_name, node_id=node_id).first()
            if existing_switch:
                flash('This node ID is already assigned for the selected fabric.', category='error')
                print("Existing switch found, not adding a new one.")
            else:
                print("Adding a new switch...")
                new_switch = CiscoACISwitch(
                    fabric_name=fabric_name,
                    node_role=node_role,
                    pod_id=pod_id,
                    node_id=node_id,
                    node_peer_id=node_peer_id,
                    serial_number=serial_number,
                    node_name=node_name
                )
                db.session.add(new_switch)
                db.session.commit()
                flash('Switch added successfully!', category='success')
                
                node_id = int(node_id)
                if node_id % 2 != 0:  # Checking if node_id is odd
                    # Querying the highest group_id
                    max_group_id = db.session.query(func.max(CiscoACISwitchVpcPairs.group_id)).filter(CiscoACISwitchVpcPairs.fabric_name == fabric_name).scalar()
                    new_group_id = 1 if max_group_id is None else max_group_id + 1
                    

application/templates/base.html
<html>
<head>
    <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
        crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />    
    <title>{% block title %}{% endblock %}</title>
    <!-- HTMX Script -->
    <script src="https://unpkg.com/htmx.org"></script>

</head>
<body>
    {% include 'navbar.html' %}
    <br/>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <!-- Bootstrap and other scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

application/templates/edit_cidr.html
<form action="{{ url_for('views.edit_cidr', id=cidr.id) }}" method="post">
    <input type="text" name="network_cidr" value="{{ cidr.network_cidr }}">
    <button type="submit" class="btn btn-success">Save</button>
</form>

application/templates/edit_cidr_app.html
<div class="container">
    <form action="{{ url_for('views.edit_cidr_app', id=cidr.id) }}" method="post">
        <div class="form-group">
            <label for="app">Application (Optional):</label>
            <input type="text" class="form-control" id="app" name="app" value="{{ cidr.application }}">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>

application/templates/edit_cidr_env.html
<form action="{{ url_for('views.edit_cidr_env', id=cidr.id) }}" method="post">
    <label for="env">Environment:</label>
    <select name="env" id="env" class="form-control">
        {% for environment in environments %}
            <option value="{{ environment.id }}" {% if environment.id == cidr.environment_id %}selected{% endif %}>
                {{ environment.types }}
            </option>
        {% endfor %}
    </select>
    <button type="submit" class="btn btn-success">Save</button>
</form>

application/templates/edit_cidr_location.html
<form action="{{ url_for('views.edit_cidr_location', id=cidr.id) }}" method="post">
    <label for="location">Location:</label>
    <select name="location" id="location" class="form-control">
        {% for location in locations %}
            <option value="{{ location.id }}" {% if location.id == cidr.location_id %} selected {% endif %}>
                {{ location.items }}
            </option>
        {% endfor %}
    </select>
    <button type="submit" class="btn btn-success">Save</button>
</form>

application/templates/edit_cidr_tenant.html
<form action="{{ url_for('views.edit_cidr_tenant', id=cidr.id) }}" method="post">
    <label for="tenant">Tenant:</label>
    <select name="tenant" id="tenant" class="form-control">
        {% for tenant in tenants %}
            <option value="{{ tenant.id }}" {% if tenant.id == cidr.tenant_id %} selected {% endif %}>
                {{ tenant.tenant_name }}
            </option>
        {% endfor %}
    </select>
    <button type="submit" class="btn btn-success">Save</button>
</form>

application/templates/edit_cidr_zone.html
<form action="{{ url_for('views.edit_cidr_zone', id=cidr.id) }}" method="post">
    <label for="zone">Zone:</label>
    <select name="zone" id="zone" class="form-control">
        {% for zone in zones %}
            <option value="{{ zone.id }}" {% if zone.id == cidr.zone_id %} selected {% endif %}>
                {{ zone.zone_name }}
            </option>
        {% endfor %}
    </select>
    <button type="submit" class="btn btn-success">Save</button>
</form>

application/templates/edit_ipam_application.html
<div class="container">
    <form action="{{ url_for('views.edit_ipam_application', host_id=host.id, cidr_id=cidr_id) }}" method="post">
        <div class="form-group">
            <label for="app">Application:</label>
            <input type="text" class="form-control" id="app" name="app" value="{{ host.application }}">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>

application/templates/edit_ipam_host_name.html
<div class="container">
    <form action="{{ url_for('views.edit_ipam_host_name', host_id=host.id) }}?cidr_id={{ cidr_id }}" method="post">
        <div class="form-group">
            <label for="host_name">host name:</label>
            <input type="text" class="form-control" id="host_name" name="host_name" value="{{ host.host_name }}">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>

application/templates/edit_switch_node_name.html
<form method="post">
    <input type="text" name="node_name" value="{{ infrastructure.node_name }}">
    <button type="submit" class="btn btn-success">Save</button>
</form>

application/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
     <!-- Card 1 -->
    <div class="col-md-3 mb-4">
      <div class="card" style="width: 18rem;">
        <img src="{{ url_for('static', filename='images/infrastructure.png') }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Infrastructure</h5>
          <p class="card-text">Click here to manage infrastructure details.</p>
          <a href="{{ url_for('views.infrastructure') }}" class="btn btn-primary">Manage</a>
        </div>
      </div>
    </div>
     <!-- Card 2 -->
    <div class="col-md-3 mb-4">
      <div class="card" style="width: 18rem;">
        <img src="{{ url_for('static', filename='images/portal.png') }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Portal</h5>
          <p class="card-text">Click here to manage portal details.</p>
          <a href="{{ url_for('views.manage_portal') }}" class="btn btn-primary">Manage</a>
        </div>
      </div>
    </div>
    <!-- Repeat for other cards -->
  </div>
  <!-- Add more rows as needed -->
</div>
{% endblock %}

application/templates/infrastructure_ipam.html
{% extends "base.html" %}
{% block title %}IPAM{% endblock %}
{% block content %}
<div class="container">
    <h2>IPAM CIDR</h2>
    <form action="" method="POST">
        <input type="hidden" name="ipam_cidrs_form" value="true"> <!-- Hidden input field for form identifier -->
        <div class="form-group">
            <label for="network_prefix">Network Prefix:</label>
            <input type="text" name="network_prefix" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="network_cidr">Network CIDR:</label>
            <input type="text" name="network_cidr" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="location">Location:</label>
            <select name="location" class="form-control">
                {% for location in locations %}
                <option value="{{ location.id }}">{{ location.items }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="tenant">Tenant:</label>
            <select name="tenant" class="form-control">
                {% for tenant in tenants %}
                <option value="{{ tenant.id }}">{{ tenant.tenant_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="zone">Zone:</label>
            <select name="zone" class="form-control">
                {% for zone in zones %}
                <option value="{{ zone.id }}">{{ zone.zone_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="environment">Environment:</label>
            <select name="environment" class="form-control">
                {% for environment in environments %}
                <option value="{{ environment.id }}">{{ environment.types }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="application">Application (Optional):</label>
            <input type="text" name="application" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Add CIDR</button>
    </form>

    <!-- Table to display IPAM CIDR records -->
    <h3>IPAM CIDR Records</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Network Prefix</th>
                <th>Network CIDR</th>
                <th>Location</th>
                <th>Tenant</th>
                <th>Zone</th>
                <th>Environment</th>
                <th>Application</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for cidr in ipam_cidrs %}
            <tr>
                <td>{{ cidr.network_prefix }}</td>
                <td hx-get="{{ url_for('views.edit_cidr', id=cidr.id) }}" hx-trigger="click">{{ cidr.network_cidr }}</td>
                <td hx-get="{{ url_for('views.edit_cidr_location', id=cidr.id) }}" hx-trigger="click">{{ cidr.location.items }}</td>
                <td hx-get="{{ url_for('views.edit_cidr_tenant', id=cidr.id) }}" hx-trigger="click">{{ cidr.tenant.tenant_name }}</td>
                <td hx-get="{{ url_for('views.edit_cidr_zone', id=cidr.id) }}" hx-trigger="click">{{ cidr.zone.zone_name }}</td>
                <td hx-get="{{ url_for('views.edit_cidr_env', id=cidr.id) }}" hx-trigger="click">{{ cidr.environment.types }}</td>
                <td hx-get="{{ url_for('views.edit_cidr_app', id=cidr.id) }}" hx-trigger="click">{{ cidr.application }}</td>
                <td>
                    <!-- Open button form -->
                    <form action="{{ url_for('views.infrastructure_ipam_hosts', id=cidr.id) }}" method="post">
                        <button type="submit" class="btn btn-Primary">Open</button>
                    </form>                    
                    <!-- Delete button form -->
                    <form action="{{ url_for('views.delete_cidr', id=cidr.id) }}" method="post">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="7">No records found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
</div>
{% endblock %}

application/templates/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://presidiofederal.com/wp-content/uploads/2021/05/main-logo.png" alt="" width="300" height="50" class="d-inline-block align-text-top">
      <b>Basic Infrastructure Portal - Presidio Federal</b>
    </a>
    <div class="navbar-nav">
      {% if current_user.is_authenticated %}
        <a class="nav-link" href="/">Home</a>
        <a class="nav-link" href="/logout">Logout</a>
      {% else %}
        <a class="nav-link" href="/login">Login</a>
        <a class="nav-link" href="/sign-up">Sign Up</a>
      {% endif %}
    </div>
  </div>
</nav>

application/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter username"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}